const data = [
  {id: 0, name: "Albania", "code": "AL"},
  {id: 1, name: "Åland Islands", "code": "AX"},
  {id: 2, name: "Algeria", "code": "DZ"},
  {id: 3, name: "American Samoa", "code": "AS"},
  {id: 4, name: "Andorra", "code": "AD"},
  {id: 5, name: "Angola", "code": "AO"},
  {id: 6, name: "Anguilla", "code": "AI"},
  {id: 7, name: "Antarctica", "code": "AQ"},
  {id: 8, name: "Antigua and Barbuda", "code": "AG"},
  {id: 9, name: "Argentina", "code": "AR"},
  {id: 10, name: "Armenia", "code": "AM"},
  {id: 11, name: "Aruba", "code": "AW"},
  {id: 12, name: "Australia", "code": "AU"},
  {id: 13, name: "Austria", "code": "AT"},
  {id: 14, name: "Azerbaijan", "code": "AZ"},
  {id: 15, name: "Bahamas (the)", "code": "BS"},
  {id: 16, name: "Bahrain", "code": "BH"},
  {id: 17, name: "Bangladesh", "code": "BD"},
  {id: 18, name: "Barbados", "code": "BB"},
  {id: 19, name: "Belarus", "code": "BY"},
  {id: 20, name: "Belgium", "code": "BE"},
  {id: 21, name: "Belize", "code": "BZ"},
  {id: 22, name: "Benin", "code": "BJ"},
  {id: 23, name: "Bermuda", "code": "BM"},
  {id: 24, name: "Bhutan", "code": "BT"},
  {id: 25, name: "Bolivia (Plurinational State of)", "code": "BO"},
  {id: 26, name: "Bonaire, Sint Eustatius and Saba", "code": "BQ"},
  {id: 27, name: "Bosnia and Herzegovina", "code": "BA"},
  {id: 28, name: "Botswana", "code": "BW"},
  {id: 29, name: "Bouvet Island", "code": "BV"},
  {id: 30, name: "Brazil", "code": "BR"},
  {id: 31, name: "British Indian Ocean Territory (the)", "code": "IO"},
  {id: 32, name: "Brunei Darussalam", "code": "BN"},
  {id: 33, name: "Bulgaria", "code": "BG"},
  {id: 34, name: "Burkina Faso", "code": "BF"},
  {id: 35, name: "Burundi", "code": "BI"},
  {id: 36, name: "Cabo Verde", "code": "CV"},
  {id: 37, name: "Cambodia", "code": "KH"},
  {id: 38, name: "Cameroon", "code": "CM"},
  {id: 39, name: "Canada", "code": "CA"},
  {id: 40, name: "Cayman Islands (the)", "code": "KY"},
  {id: 41, name: "Central African Republic (the)", "code": "CF"},
  {id: 42, name: "Chad", "code": "TD"},
  {id: 43, name: "Chile", "code": "CL"},
  {id: 44, name: "China", "code": "CN"},
  {id: 45, name: "Christmas Island", "code": "CX"},
  {id: 46, name: "Cocos (Keeling) Islands (the)", "code": "CC"},
  {id: 47, name: "Colombia", "code": "CO"},
  {id: 48, name: "Comoros (the)", "code": "KM"},
  {id: 49, name: "Congo (the Democratic Republic of the)", "code": "CD"},
  {id: 50, name: "Congo (the)", "code": "CG"},
  {id: 51, name: "Cook Islands (the)", "code": "CK"},
  {id: 52, name: "Costa Rica", "code": "CR"},
  {id: 53, name: "Croatia", "code": "HR"},
  {id: 54, name: "Cuba", "code": "CU"},
  {id: 55, name: "Curaçao", "code": "CW"},
  {id: 56, name: "Cyprus", "code": "CY"},
  {id: 57, name: "Czechia", "code": "CZ"},
  {id: 58, name: "Côte d'Ivoire", "code": "CI"},
  {id: 59, name: "Denmark", "code": "DK"},
  {id: 60, name: "Djibouti", "code": "DJ"},
  {id: 61, name: "Dominica", "code": "DM"},
  {id: 62, name: "Dominican Republic (the)", "code": "DO"},
  {id: 63, name: "Ecuador", "code": "EC"},
  {id: 64, name: "Egypt", "code": "EG"},
  {id: 65, name: "El Salvador", "code": "SV"},
  {id: 66, name: "Equatorial Guinea", "code": "GQ"},
  {id: 67, name: "Eritrea", "code": "ER"},
  {id: 68, name: "Estonia", "code": "EE"},
  {id: 69, name: "Eswatini", "code": "SZ"},
  {id: 70, name: "Ethiopia", "code": "ET"},
  {id: 71, name: "Falkland Islands (the) [Malvinas]", "code": "FK"},
  {id: 72, name: "Faroe Islands (the)", "code": "FO"},
  {id: 73, name: "Fiji", "code": "FJ"},
  {id: 74, name: "Finland", "code": "FI"},
  {id: 75, name: "France", "code": "FR"},
  {id: 76, name: "French Guiana", "code": "GF"},
  {id: 77, name: "French Polynesia", "code": "PF"},
  {id: 78, name: "French Southern Territories (the)", "code": "TF"},
  {id: 79, name: "Gabon", "code": "GA"},
  {id: 80, name: "Gambia (the)", "code": "GM"},
  {id: 81, name: "Georgia", "code": "GE"},
  {id: 82, name: "Germany", "code": "DE"},
  {id: 83, name: "Ghana", "code": "GH"},
  {id: 84, name: "Gibraltar", "code": "GI"},
  {id: 85, name: "Greece", "code": "GR"},
  {id: 86, name: "Greenland", "code": "GL"},
  {id: 87, name: "Grenada", "code": "GD"},
  {id: 88, name: "Guadeloupe", "code": "GP"},
  {id: 89, name: "Guam", "code": "GU"},
  {id: 90, name: "Guatemala", "code": "GT"},
  {id: 91, name: "Guernsey", "code": "GG"},
  {id: 92, name: "Guinea", "code": "GN"},
  {id: 93, name: "Guinea-Bissau", "code": "GW"},
  {id: 94, name: "Guyana", "code": "GY"},
  {id: 95, name: "Haiti", "code": "HT"},
  {id: 96, name: "Heard Island and McDonald Islands", "code": "HM"},
  {id: 97, name: "Holy See (the)", "code": "VA"},
  {id: 98, name: "Honduras", "code": "HN"},
  {id: 99, name: "Hong Kong", "code": "HK"},
  {id: 100, name: "Hungary", "code": "HU"},
  {id: 101, name: "Iceland", "code": "IS"},
  {id: 102, name: "India", "code": "IN"},
  {id: 103, name: "Indonesia", "code": "ID"},
  {id: 104, name: "Iran (Islamic Republic of)", "code": "IR"},
  {id: 105, name: "Iraq", "code": "IQ"},
  {id: 106, name: "Ireland", "code": "IE"},
  {id: 107, name: "Isle of Man", "code": "IM"},
  {id: 108, name: "Israel", "code": "IL"},
  {id: 109, name: "Italy", "code": "IT"},
  {id: 110, name: "Jamaica", "code": "JM"},
  {id: 111, name: "Japan", "code": "JP"},
  {id: 112, name: "Jersey", "code": "JE"},
  {id: 113, name: "Jordan", "code": "JO"},
  {id: 114, name: "Kazakhstan", "code": "KZ"},
  {id: 115, name: "Kenya", "code": "KE"},
  {id: 116, name: "Kiribati", "code": "KI"},
  {id: 117, name: "Korea (the Democratic People's Republic of)", "code": "KP"},
  {id: 118, name: "Korea (the Republic of)", "code": "KR"},
  {id: 119, name: "Kuwait", "code": "KW"},
  {id: 120, name: "Kyrgyzstan", "code": "KG"},
  {id: 121, name: "Lao People's Democratic Republic (the)", "code": "LA"},
  {id: 122, name: "Latvia", "code": "LV"},
  {id: 123, name: "Lebanon", "code": "LB"},
  {id: 124, name: "Lesotho", "code": "LS"},
  {id: 125, name: "Liberia", "code": "LR"},
  {id: 126, name: "Libya", "code": "LY"},
  {id: 127, name: "Liechtenstein", "code": "LI"},
  {id: 128, name: "Lithuania", "code": "LT"},
  {id: 129, name: "Luxembourg", "code": "LU"},
  {id: 130, name: "Macao", "code": "MO"},
  {id: 131, name: "Madagascar", "code": "MG"},
  {id: 132, name: "Malawi", "code": "MW"},
  {id: 133, name: "Malaysia", "code": "MY"},
  {id: 134, name: "Maldives", "code": "MV"},
  {id: 135, name: "Mali", "code": "ML"},
  {id: 136, name: "Malta", "code": "MT"},
  {id: 137, name: "Marshall Islands (the)", "code": "MH"},
  {id: 138, name: "Martinique", "code": "MQ"},
  {id: 139, name: "Mauritania", "code": "MR"},
  {id: 140, name: "Mauritius", "code": "MU"},
  {id: 141, name: "Mayotte", "code": "YT"},
  {id: 142, name: "Mexico", "code": "MX"},
  {id: 143, name: "Micronesia (Federated States of)", "code": "FM"},
  {id: 144, name: "Moldova (the Republic of)", "code": "MD"},
  {id: 145, name: "Monaco", "code": "MC"},
  {id: 146, name: "Mongolia", "code": "MN"},
  {id: 147, name: "Montenegro", "code": "ME"},
  {id: 148, name: "Montserrat", "code": "MS"},
  {id: 149, name: "Morocco", "code": "MA"},
  {id: 150, name: "Mozambique", "code": "MZ"},
  {id: 151, name: "Myanmar", "code": "MM"},
  {id: 152, name: "Namibia", "code": "NA"},
  {id: 153, name: "Nauru", "code": "NR"},
  {id: 154, name: "Nepal", "code": "NP"},
  {id: 155, name: "Netherlands (the)", "code": "NL"},
  {id: 156, name: "New Caledonia", "code": "NC"},
  {id: 157, name: "New Zealand", "code": "NZ"},
  {id: 158, name: "Nicaragua", "code": "NI"},
  {id: 159, name: "Niger (the)", "code": "NE"},
  {id: 160, name: "Nigeria", "code": "NG"},
  {id: 161, name: "Niue", "code": "NU"},
  {id: 162, name: "Norfolk Island", "code": "NF"},
  {id: 163, name: "Northern Mariana Islands (the)", "code": "MP"},
  {id: 164, name: "Norway", "code": "NO"},
  {id: 165, name: "Oman", "code": "OM"},
  {id: 166, name: "Pakistan", "code": "PK"},
  {id: 167, name: "Palau", "code": "PW"},
  {id: 168, name: "Palestine, State of", "code": "PS"},
  {id: 169, name: "Panama", "code": "PA"},
  {id: 170, name: "Papua New Guinea", "code": "PG"},
  {id: 171, name: "Paraguay", "code": "PY"},
  {id: 172, name: "Peru", "code": "PE"},
  {id: 173, name: "Philippines (the)", "code": "PH"},
  {id: 174, name: "Pitcairn", "code": "PN"},
  {id: 175, name: "Poland", "code": "PL"},
  {id: 176, name: "Portugal", "code": "PT"},
  {id: 177, name: "Puerto Rico", "code": "PR"},
  {id: 178, name: "Qatar", "code": "QA"},
  {id: 179, name: "Republic of North Macedonia", "code": "MK"},
  {id: 180, name: "Romania", "code": "RO"},
  {id: 181, name: "Russian Federation (the)", "code": "RU"},
  {id: 182, name: "Rwanda", "code": "RW"},
  {id: 183, name: "Réunion", "code": "RE"},
  {id: 184, name: "Saint Barthélemy", "code": "BL"},
  {id: 185, name: "Saint Helena, Ascension and Tristan da Cunha", "code": "SH"},
  {id: 186, name: "Saint Kitts and Nevis", "code": "KN"},
  {id: 187, name: "Saint Lucia", "code": "LC"},
  {id: 188, name: "Saint Martin (French part)", "code": "MF"},
  {id: 189, name: "Saint Pierre and Miquelon", "code": "PM"},
  {id: 190, name: "Saint Vincent and the Grenadines", "code": "VC"},
  {id: 191, name: "Samoa", "code": "WS"},
  {id: 192, name: "San Marino", "code": "SM"},
  {id: 193, name: "Sao Tome and Principe", "code": "ST"},
  {id: 194, name: "Saudi Arabia", "code": "SA"},
  {id: 195, name: "Senegal", "code": "SN"},
  {id: 196, name: "Serbia", "code": "RS"},
  {id: 197, name: "Seychelles", "code": "SC"},
  {id: 198, name: "Sierra Leone", "code": "SL"},
  {id: 199, name: "Singapore", "code": "SG"},
  {id: 201, name: "Sint Maarten (Dutch part)", "code": "SX"},
  {id: 202, name: "Slovakia", "code": "SK"},
  {id: 203, name: "Slovenia", "code": "SI"},
  {id: 204, name: "Solomon Islands", "code": "SB"},
  {id: 205, name: "Somalia", "code": "SO"},
  {id: 206, name: "South Africa", "code": "ZA"},
  {id: 207, name: "South Georgia and the South Sandwich Islands", "code": "GS"},
  {id: 208, name: "South Sudan", "code": "SS"},
  {id: 209, name: "Spain", "code": "ES"},
  {id: 210, name: "Sri Lanka", "code": "LK"},
  {id: 211, name: "Sudan (the)", "code": "SD"},
  {id: 212, name: "Suriname", "code": "SR"},
  {id: 213, name: "Svalbard and Jan Mayen", "code": "SJ"},
  {id: 214, name: "Sweden", "code": "SE"},
  {id: 215, name: "Switzerland", "code": "CH"},
  {id: 216, name: "Syrian Arab Republic", "code": "SY"},
  {id: 217, name: "Taiwan (Province of China)", "code": "TW"},
  {id: 218, name: "Tajikistan", "code": "TJ"},
  {id: 219, name: "Tanzania, United Republic of", "code": "TZ"},
  {id: 220, name: "Thailand", "code": "TH"},
  {id: 221, name: "Timor-Leste", "code": "TL"},
  {id: 222, name: "Togo", "code": "TG"},
  {id: 223, name: "Tokelau", "code": "TK"},
  {id: 224, name: "Tonga", "code": "TO"},
  {id: 225, name: "Trinidad and Tobago", "code": "TT"},
  {id: 226, name: "Tunisia", "code": "TN"},
  {id: 227, name: "Turkey", "code": "TR"},
  {id: 228, name: "Turkmenistan", "code": "TM"},
  {id: 229, name: "Turks and Caicos Islands (the)", "code": "TC"},
  {id: 230, name: "Tuvalu", "code": "TV"},
  {id: 231, name: "Uganda", "code": "UG"},
  {id: 232, name: "Ukraine", "code": "UA"},
  {id: 233, name: "United Arab Emirates (the)", "code": "AE"},
  {id: 234, name: "United Kingdom of Great Britain and Northern Ireland (the)", "code": "GB"},
  {id: 235, name: "United States Minor Outlying Islands (the)", "code": "UM"},
  {id: 236, name: "United States of America (the)", "code": "US"},
  {id: 237, name: "Uruguay", "code": "UY"},
  {id: 238, name: "Uzbekistan", "code": "UZ"},
  {id: 239, name: "Vanuatu", "code": "VU"},
  {id: 240, name: "Venezuela (Bolivarian Republic of)", "code": "VE"},
  {id: 241, name: "Viet Nam", "code": "VN"},
  {id: 242, name: "Virgin Islands (British)", "code": "VG"},
  {id: 243, name: "Virgin Islands (U.S.)", "code": "VI"},
  {id: 244, name: "Wallis and Futuna", "code": "WF"},
  {id: 245, name: "Western Sahara", "code": "EH"},
  {id: 246, name: "Yemen", "code": "YE"},
  {id: 247, name: "Zambia", "code": "ZM"},
  {id: 248, name: "Zimbabwe", "code": "ZW"}
]

export default data;